<?php


/**
 * Implements hook_views_pre_build().
 */
function custom_views_pre_build(&$view) {

 $account = user_load($GLOBALS['user']->uid);
 $topic_ids = '';
 if(!empty($account->field_topic))
 {  
   $topic_ids=$account->field_topic['und'][0]['target_id'];  
 }

 if ($view->name == 'workbench_moderation' && $view->current_display == 'needs_review_page') {
  // Set the first contextual filter value.
  $view->args[0] = $topic_ids;
 }

}



?>